### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by ResidentMario** [mdezube/sms-analysis#10]
Hey, sorry for dropping this as an issue but I didn't find an easier way of contacting you after a quick search.

I saw the topic of your presentation for the upcoming January D3.JS meetup (I gave a presentation there ~October), and wanted to point out a small glue library I built called [`py_d3`](https://github.com/ResidentMario/py_d3) which makes doing `d3` inside of `jupyter` a bit easier. You may find it useful for future hacks!

**Comment by mdezube** [comment]
Hey Mario,

The library looks cool, I'll definitely play around with it for hacking.  As regards to this project, I prefer having d3 local as opposed to making this network call since it makes it more readily useable.

Also that's cool that you presented!  What was the topic?  Also let's break this discussion to email, my email address is in the README of this project, but for quick reference it's michael dezube at gmail dot com.
